### ISSUE TITLE
ERR_REQUIRE_ESM after php artisan krakero:tailwind-config

### ISSUE THREAD

**Issue by netwaretcs** [kraKero/tailwind-fieldtype#6] opened 2023-11-22 09:06 UTC
`Error [ERR_REQUIRE_ESM]: require() of ES Module`

in 

`/home/username/app/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js:15
const tailwindConfig = require(path.normalize(`${process.cwd()}/${argv.config}`));
`

Node.js v18.14.2

**Comment by vmitchell85** [comment] 2023-11-22 14:11
@netwaretcs This seems to be a duplicate of #1 ...

Can you post your `tailwind.config.js` file?

**Comment by vmitchell85** [comment] 2023-12-11 01:54
closing since no response. If this is different just reopen.

**Closed as completed by vmitchell85** 2023-12-11 01:54 UTC
